Repository VeryGoodOpenSource/very_good_cli, pull requests merged in 2021-09, with the labels that each got.

#177 chore: v0.4.2
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#185 feat(core): upgrade dependencies
  lib/src/templates/very_good_core_bundle.dart
Labels: enhancement

#186 chore: v0.4.3
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#187 feat(core): bloc v7.2.0 and internal platform updates
  lib/src/templates/very_good_core_bundle.dart
Labels: enhancement

#181 feat: add auto update
  lib/src/command_runner.dart
  pubspec.yaml
  test/src/command_runner_test.dart
  test/src/commands/create_test.dart
Labels: enhancement

#188 refactor: modularize cli utilities
  lib/src/cli/cli.dart
  lib/src/cli/flutter_cli.dart
  lib/src/templates/template.dart
  test/src/cmd_test.dart
Labels: refactor

#189 feat: run dart fix --apply as post generation step
  .github/workflows/very_good_cli.yaml
  dart_test.yaml
  lib/src/cli/cli.dart
  lib/src/cli/dart_cli.dart
  lib/src/cli/flutter_cli.dart
  lib/src/templates/template.dart
  test/e2e_test.dart
  test/src/cli/dart_cli_test.dart
  test/src/cli/flutter_cli_test.dart
  test/src/commands/create_test.dart
Labels: enhancement, refactor

#190 chore(deps): upgrade to mason ^0.0.1-dev.48
  pubspec.yaml
Labels: chore

#191 feat(core): template improvements
  lib/src/templates/very_good_core_bundle.dart
Labels: enhancement

#192 chore: v0.4.4
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#194 chore: upgrade to mason v0.0.1-dev.51
  pubspec.yaml
Labels: chore

#197 fix(core): MainActivity.kt not found
  .github/workflows/very_good_cli.yaml
  lib/src/commands/create.dart
  lib/src/templates/dart_package_bundle.dart
  lib/src/templates/flutter_package_bundle.dart
  lib/src/templates/very_good_core_bundle.dart
  pubspec.yaml
  test/src/commands/create_test.dart
Labels: bug

#195 feat(flutter_plugin): conditional platform support
  lib/src/commands/create.dart
  lib/src/templates/flutter_plugin_bundle.dart
  test/src/commands/create_test.dart
Labels: refactor

#198 chore: v0.4.5
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore
