Repository VeryGoodOpenSource/very_good_cli, pull requests merged in 2021-07, with the labels that each got.

#148 feat: support custom org name
  lib/src/commands/create.dart
  test/src/commands/create_test.dart
Labels: enhancement

#152 feat: l10n non-nullable getter + variable org name segment length
  lib/src/templates/very_good_core_bundle.dart
Labels: enhancement

#153 chore: v0.2.5
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#154 feat: add support for dart and flutter package MasonBundles
  README.md
  lib/src/commands/create.dart
  lib/src/flutter_cli.dart
  lib/src/templates/dart_package_bundle.dart
  lib/src/templates/flutter_package_bundle.dart
  lib/src/templates/template.dart
  lib/src/templates/templates.dart
  test/src/cmd_test.dart
  test/src/commands/create_test.dart
Labels: enhancement

#155 chore: v0.3.0
  CHANGELOG.md
  README.md
  lib/src/commands/create.dart
  lib/src/templates/template.dart
  lib/src/version.dart
  pubspec.yaml
  test/src/command_runner_test.dart
  test/src/commands/create_test.dart
Labels: chore, documentation

#159 chore: minor updates to usage descriptions
  README.md
  lib/src/commands/create.dart
  lib/src/templates/template.dart
  test/src/commands/create_test.dart
Labels: chore

#160 chore: v0.3.1
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore
