Repository VeryGoodOpenSource/very_good_cli, pull requests merged in 2021-02, with the labels that each got.

#74 chore: bump to v0.1.1
  CHANGELOG.md
  README.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#75 docs: update pub global command
  README.md
  example/README.md
  lib/very_good_cli.dart
Labels: documentation

#76 docs: add pub.dev badge to README
  README.md
Labels: documentation

#78 docs(very_good_core): improve README
  doc/very_good_core.md
Labels: documentation

#83 feat: improve analytics option usage
  README.md
  lib/src/command_runner.dart
  test/src/command_runner_test.dart
Labels: enhancement

#84 feat: improve create command usage
  README.md
  lib/src/commands/create.dart
  test/src/command_runner_test.dart
Labels: enhancement

#85 docs: add note to use beta channel to README
  README.md
  doc/very_good_core.md
Labels: documentation

#87 docs(very_good_core): add flavor entry point explanation
  doc/very_good_core.md
Labels: documentation

#88 chore: v0.1.2
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#89 chore: remove unused excludes from analysis_options.yaml
  analysis_options.yaml
Labels: chore

#99 docs: add gif and link to blog
  README.md
  doc/assets/very_good_create.gif
Labels: documentation
