Repository VeryGoodOpenSource/very_good_cli, pull requests merged in 2021-08, with the labels that each got.

#163 chore: v0.3.2
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#167 chore: v0.3.3
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#168 refactor: use very_good_analysis v2.3.0
  analysis_options.yaml
  bin/very_good.dart
  lib/src/command_runner.dart
  lib/src/commands/create.dart
  lib/src/templates/dart_package_bundle.dart
  lib/src/templates/flutter_package_bundle.dart
  lib/src/templates/template.dart
  lib/src/templates/very_good_core_bundle.dart
  pubspec.yaml
  test/src/commands/create_test.dart
Labels: refactor

#169 feat: add template for creating a flutter plugin
  lib/src/commands/create.dart
  lib/src/flutter_cli.dart
  lib/src/templates/flutter_plugin_bundle.dart
  lib/src/templates/template.dart
  lib/src/templates/templates.dart
  test/src/cmd_test.dart
  test/src/commands/create_test.dart
Labels: enhancement

#170 chore: v0.4.0
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#172 feat(core): upgrade to flutter_bloc v7.2.0
  lib/src/templates/very_good_core_bundle.dart
Labels: enhancement

#173 chore: v0.4.1
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore
