Repository VeryGoodOpenSource/very_good_cli, pull requests merged in 2022-02, with the labels that each got.

#268 fix(flutter_plugin): remove duplicate android directory
  lib/src/templates/flutter_plugin/flutter_plugin_bundle.dart
Labels: bug

#270 chore: v0.4.17
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#274 feat(core): upgrade to Flutter v2.10.0
  lib/src/templates/very_good_core/very_good_core_bundle.dart
Labels: enhancement

#275 chore: v0.5.0
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#276 feat(dart_package): upgrade to Dart 2.16
  lib/src/templates/dart_package/dart_package_bundle.dart
Labels: enhancement

#277 feat(flutter_package): upgrade to Dart 2.16
  lib/src/templates/flutter_package/flutter_package_bundle.dart
Labels: enhancement

#283 fix(packages_get): recursive installation ignored directories fixes
  lib/src/cli/cli.dart
  test/src/commands/packages_test.dart
Labels: bug

#284 chore: v0.5.1
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#287 feat(core): windows support
  lib/src/templates/very_good_core/very_good_core_bundle.dart
Labels: enhancement

#288 docs(README): add windows to supported platforms
  README.md
Labels: documentation

#289 chore: v0.5.2
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#291 fix(core): android 12 builds
  lib/src/templates/very_good_core/very_good_core_bundle.dart
Labels: bug

#292 chore: v0.5.3
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#296 refactor: upgrade to mason 0.1.0-dev.8
  lib/src/command_runner.dart
  lib/src/commands/create.dart
  pubspec.yaml
  test/src/command_runner_test.dart
  test/src/commands/create_test.dart
Labels: refactor

#298 fix: add description variable to index.html #297
  lib/src/templates/very_good_core/very_good_core_bundle.dart
Labels: bug

#299 chore(deps): upgrade to mason v0.1.0-dev.9
  pubspec.yaml
Labels: chore

#300 chore: v0.5.4
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore
