Repository VeryGoodOpenSource/very_good_cli, pull requests merged in 2022-03, with the labels that each got.

#301 feat(core): upgrade mocktail, bloc, and bloc_test
  lib/src/templates/very_good_core/very_good_core_bundle.dart
Labels: enhancement

#302 chore: v0.5.5
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#303 feat: adding very_good test command
  README.md
  lib/src/cli/flutter_cli.dart
  lib/src/command_runner.dart
  lib/src/commands/commands.dart
  lib/src/commands/test.dart
  test/src/cli/flutter_cli_test.dart
  test/src/command_runner_test.dart
  test/src/commands/command_helper.dart
  test/src/commands/test_test.dart
Labels: enhancement

#304 refactor: standardize tests to use withRunner helper
  test/helpers/command_helper.dart
  test/helpers/helpers.dart
  test/src/commands/create_test.dart
  test/src/commands/packages_test.dart
  test/src/commands/test_test.dart
Labels: refactor

#307 fix: add .fvm to ignored directories for pubspec files searching
  lib/src/cli/cli.dart
  test/src/commands/packages_test.dart
Labels: bug

#308 feat: use very_good_test_runner to improve test output
  lib/src/cli/cli.dart
  lib/src/cli/dart_cli.dart
  lib/src/cli/flutter_cli.dart
  lib/src/commands/test.dart
  pubspec.yaml
  test/src/cli/flutter_cli_test.dart
  test/src/commands/test_test.dart
Labels: enhancement

#309 fix(test): truncate output to fit line
  lib/src/cli/flutter_cli.dart
  test/src/cli/flutter_cli_test.dart
Labels: bug

#310 chore: v0.6.0-dev.1
  CHANGELOG.md
  lib/src/cli/flutter_cli.dart
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#305 feat(test): add `--coverage` and `--min coverage` options
  README.md
  lib/src/cli/cli.dart
  lib/src/cli/flutter_cli.dart
  lib/src/commands/test.dart
  pubspec.yaml
  test/src/cli/flutter_cli_test.dart
  test/src/commands/test_test.dart
Labels: enhancement

#313 feat(test): support specific test execution
  README.md
  lib/src/cli/flutter_cli.dart
  lib/src/commands/test.dart
  test/src/commands/test_test.dart
Labels: enhancement

#314 feat(test): add --exclude-tags option
  README.md
  lib/src/commands/test.dart
  test/src/commands/test_test.dart
Labels: enhancement

#318 feat(test): performance optimizations
  .github/workflows/very_good_cli.yaml
  lib/src/cli/cli.dart
  lib/src/cli/flutter_cli.dart
  lib/src/commands/commands.dart
  lib/src/commands/create/create.dart
  lib/src/commands/test/templates/test_runner_bundle.dart
  lib/src/commands/test/test.dart
  pubspec.yaml
  test/src/cli/flutter_cli_test.dart
  test/src/commands/create/create_test.dart
  test/src/commands/test/test_test.dart
  test/src/commands/test_test.dart
Labels: enhancement

#319 chore: v0.6.0
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#322 fix(test): run tests with --no-pub
  lib/src/commands/test/test.dart
  test/src/commands/test/test_test.dart
Labels: bug

#323 feat(test): remove .test_runner.dart after run
  lib/src/cli/flutter_cli.dart
  test/src/cli/flutter_cli_test.dart
Labels: enhancement

#325 feat(test): add --no-optimization flag
  README.md
  lib/src/commands/test/test.dart
  test/src/commands/test/test_test.dart
Labels: enhancement

#326 feat(test): add --test-randomize-ordering-seed
  README.md
  lib/src/commands/test/test.dart
  test/src/commands/test/test_test.dart
Labels: enhancement

#329 fix(test): test_runner runs tests in isolated groups
  lib/src/cli/flutter_cli.dart
  lib/src/commands/test/templates/test_runner_bundle.dart
  test/src/cli/flutter_cli_test.dart
Labels: bug

#330 chore: v0.6.1
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#333 fix(test): resolve range error when truncating due to whitespace
  lib/src/cli/flutter_cli.dart
  test/src/cli/flutter_cli_test.dart
Labels: bug

#334 chore: v0.6.2
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#337 fix(test): flutter_test compatibility
  lib/src/commands/test/templates/test_runner_bundle.dart
  test/src/cli/flutter_cli_test.dart
Labels: bug

#338 chore: v0.6.3
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#340 fix(test): output random seed when specified
  lib/src/cli/flutter_cli.dart
  lib/src/commands/test/test.dart
  test/src/cli/flutter_cli_test.dart
  test/src/commands/test/test_test.dart
Labels: bug

#341 feat(test): add --update-goldens
  README.md
  lib/src/commands/test/test.dart
  test/src/commands/test/test_test.dart
Labels: enhancement

#342 chore: v0.6.4
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#344 fix(test): exit (non-zero) on test failure
  lib/src/cli/cli.dart
  lib/src/cli/flutter_cli.dart
  lib/src/commands/test/test.dart
  test/src/cli/flutter_cli_test.dart
  test/src/commands/test/test_test.dart
Labels: bug

#348 fix(test): cleanup .test_runner.dart on failure
  lib/src/cli/flutter_cli.dart
  test/src/cli/flutter_cli_test.dart
Labels: bug

#350 chore: v0.6.5
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
  test/src/cli/flutter_cli_test.dart
Labels: chore
