Repository VeryGoodOpenSource/very_good_cli, pull requests merged in 2022-06, with the labels that each got.

#388 fix: run golden tests with test optimization enabled
  lib/src/commands/test/templates/test_runner_bundle.dart
Labels: bug

#429 feat(create): upgrade templates to very_good_analysis v3.0.1
  lib/src/commands/create/templates/dart_package/dart_package_bundle.dart
  lib/src/commands/create/templates/flutter_package/flutter_package_bundle.dart
  lib/src/commands/create/templates/flutter_plugin/flutter_plugin_bundle.dart
  lib/src/commands/create/templates/very_good_core/very_good_core_bundle.dart
  pubspec.yaml
Labels: enhancement

#421 feat(test): support `--tags` option
  lib/src/commands/test/test.dart
  test/src/commands/test/test_test.dart
Labels: enhancement

#430 chore: v0.7.7
  CHANGELOG.md
  lib/src/commands/test/test.dart
  lib/src/version.dart
  pubspec.yaml
  test/src/commands/test/test_test.dart
Labels: chore

#436 fix(create): run pre-gen hooks
  lib/src/commands/create/create.dart
  test/src/commands/create/create_test.dart
Labels: bug

#438 chore: v0.7.8
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#440 refactor(dart_cli): stub process.run in unit tests
  lib/src/cli/cli.dart
  test/src/cli/dart_cli_test.dart
  test/src/cli/process_overrides_test.dart
Labels: refactor

#441 refactor(git_cli): stub process.run in unit tests
  test/src/cli/git_cli_test.dart
Labels: refactor

#443 refactor(flutter_cli): stub process.run in unit tests
  test/src/cli/flutter_cli_test.dart
Labels: refactor

#444 refactor(flutter_cli): stub test runner in unit tests
  lib/src/cli/flutter_cli.dart
  test/fixtures/fixtures.dart
  test/fixtures/lcov_fixtures.dart
  test/fixtures/test_runner_fixtures.dart
  test/src/cli/flutter_cli_test.dart
Labels: refactor

#445 feat(very_good_dart_cli): add update command
  lib/src/commands/create/templates/very_good_dart_cli/very_good_dart_cli_bundle.dart
Labels: enhancement

#446 ci: use semantic-pull-request workflow
  .github/workflows/ci.yaml
Labels: ci

#447 feat: enhance upgrade prompt to use very_good update
  lib/src/command_runner.dart
  test/src/command_runner_test.dart
Labels: enhancement
