Repository VeryGoodOpenSource/very_good_cli, pull requests merged in 2022-11, with the labels that each got.

#539 fix: only animate stdout progress on terminals
  pubspec.yaml
Labels: bug, chore

#540 chore: v0.8.3
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#547 docs: add flame_game to README
  README.md
Labels: documentation

#558 chore(deps): upgrade to docusaurus 2.2.0
  site/package-lock.json
  site/package.json
Labels: chore

#560 docs: minor improvements to docs site documentation
  README.md
  site/docs/templates/docs_site.md
Labels: documentation

#555 feat(core): support application_id argument
  lib/src/commands/create/create.dart
  lib/src/commands/create/templates/very_good_core/very_good_core_bundle.dart
  lib/src/commands/create/templates/very_good_dart_cli/very_good_dart_cli_bundle.dart
  lib/src/commands/create/templates/very_good_dart_package/very_good_dart_package_bundle.dart
  lib/src/commands/create/templates/very_good_flutter_package/very_good_flutter_package_bundle.dart
  lib/src/commands/create/templates/very_good_flutter_plugin/very_good_flutter_plugin_bundle.dart
  test/src/commands/create/create_test.dart
Labels: enhancement

#577 ci: add spell check workflow
  .github/cspell.json
  .github/workflows/ci.yaml
Labels: ci
