Repository VeryGoodOpenSource/very_good_cli, pull requests merged in 2023-10, with the labels that each got.

#817 feat(spdx_license): include tryParse
  bricks/spdx_license/__brick__/spdx_license.gen.dart
Labels: enhancement

#828 refactor: move spdx_license brick under tool
  .github/dependabot.yaml
  .github/workflows/spdx_license.yaml
  mason.yaml
  tool/spdx_license/CONTRIBUTING.md
  tool/spdx_license/README.md
  tool/spdx_license/__brick__/spdx_license.gen.dart
  tool/spdx_license/analysis_options.yaml
  tool/spdx_license/brick.yaml
  tool/spdx_license/hooks/analysis_options.yaml
  tool/spdx_license/hooks/dart_test.yaml
  tool/spdx_license/hooks/pre_gen.dart
  tool/spdx_license/hooks/pubspec.yaml
  tool/spdx_license/hooks/test/pre_gen_test.dart
  tool/spdx_license/pubspec.yaml
  tool/spdx_license/test/spdx_license.gen.dart
  tool/spdx_license/test/spdx_license_test.dart
Labels: refactor

#829 refactor: moved packages get command to its own file
  lib/src/commands/commands.dart
  lib/src/commands/packages/commands/commands.dart
  lib/src/commands/packages/commands/get.dart
  lib/src/commands/packages/packages.dart
  test/src/commands/packages/commands/get_test.dart
  test/src/commands/packages/packages_test.dart
  test/src/commands/packages_test.dart
Labels: refactor

#832 refactor: reduced new objects when parsing SpdxLicense
  tool/spdx_license/__brick__/spdx_license.gen.dart
  tool/spdx_license/test/spdx_license.gen.dart
Labels: refactor

#834 chore: update SPDX licenses
  tool/spdx_license/test/spdx_license.gen.dart
Labels: chore

#836 ci: deffer reviewers to codeowners on bump_templates
  .github/workflows/bump_templates.yaml
Labels: ci

#835 ci: include workflow to commit SPDX updates as bot
  .github/workflows/spdx_license_bot.yaml
Labels: ci

#839 chore: request code ownership
  .github/CODEOWNERS
Labels: chore

#818 feat: defined PubLicense to get packages' licenses
  analysis_options.yaml
  lib/src/pub_license/pub_license.dart
  pubspec.yaml
  test/src/pub_license/fixtures/generate_pub_license_fixtures.dart
  test/src/pub_license/fixtures/multipleLicense.html
  test/src/pub_license/fixtures/noLicense.html
  test/src/pub_license/fixtures/singleLicense.html
  test/src/pub_license/pub_license_test.dart
Labels: enhancement

#833 docs: documented sdpx build_hooks workflow
  .github/workflows/spdx_license.yaml
Labels: refactor

#841 feat: include hidden check licenses command
  lib/src/commands/packages/commands/check/check.dart
  lib/src/commands/packages/commands/check/commands/commands.dart
  lib/src/commands/packages/commands/check/commands/licenses.dart
  lib/src/commands/packages/packages.dart
  test/src/commands/packages/commands/check/check_test.dart
  test/src/commands/packages/commands/check/commands/licenses_test.dart
Labels: enhancement

#840 docs: documented very_good test argument terminator
  site/docs/commands/test.md
Labels: documentation

#842 feat: allow `packages check licenses` to fetch licenses
  lib/src/commands/packages/commands/check/commands/licenses.dart
  lib/src/pub_license/pub_license.dart
  pubspec.yaml
  test/helpers/command_helper.dart
  test/src/commands/packages/commands/check/commands/licenses_test.dart
Labels: enhancement

#846 feat: add `--ignore-failures` to `check licenses`
  lib/src/commands/packages/commands/check/commands/licenses.dart
  test/src/commands/packages/commands/check/commands/licenses_test.dart
Labels: enhancement

#847 feat: add `--dependency-type` to `check licenses`
  lib/src/commands/packages/commands/check/commands/licenses.dart
  test/src/commands/packages/commands/check/commands/licenses_test.dart
Labels: enhancement

#848 feat: add `--allowed` to `check licenses`
  lib/src/commands/packages/commands/check/commands/licenses.dart
  test/src/commands/packages/commands/check/commands/licenses_test.dart
Labels: enhancement

#850 feat: add `--forbidden` to `check licenses`
  lib/src/commands/packages/commands/check/commands/licenses.dart
  test/src/commands/packages/commands/check/commands/licenses_test.dart
Labels: enhancement

#858 feat: rename `ignore-failures` to `ignore-retrieval-failures`
  lib/src/commands/packages/commands/check/commands/licenses.dart
  test/src/commands/packages/commands/check/commands/licenses_test.dart
Labels: enhancement

#856 feat: include license count upon `check licenses` progress completion
  lib/src/commands/packages/commands/check/commands/licenses.dart
  test/src/commands/packages/commands/check/commands/licenses_test.dart
Labels: enhancement

#857 docs: update forbidden and allowed options help message
  lib/src/commands/packages/commands/check/commands/licenses.dart
  test/src/commands/packages/commands/check/commands/licenses_test.dart
Labels: documentation

#855 feat: modified collection progress message on `check license`
  lib/src/commands/packages/commands/check/commands/licenses.dart
  test/src/commands/packages/commands/check/commands/licenses_test.dart
Labels: enhancement

#862 feat: show `check licenses` command
  lib/src/commands/packages/commands/check/check.dart
  lib/src/commands/packages/commands/check/commands/licenses.dart
  test/src/commands/packages/commands/check/check_test.dart
  test/src/commands/packages/commands/check/commands/licenses_test.dart
  test/src/commands/packages/packages_test.dart
Labels: enhancement

#865 chore: v0.17.0
  .github/cspell.json
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore

#863 docs: update supported licenses reference
  site/docs/commands/check_licenses.md
Labels: documentation

#867 docs: add license checking documentation to commands' overview
  README.md
  lib/src/commands/packages/commands/check/commands/licenses.dart
  site/docs/overview.md
  test/src/commands/packages/commands/check/check_test.dart
  test/src/commands/packages/commands/check/commands/licenses_test.dart
Labels: documentation
