Repository VeryGoodOpenSource/very_good_cli, pull requests merged in 2023-12, with the labels that each got.

#922 docs(cli): Update CLI output text for clarity
  lib/src/commands/create/templates/very_good_core/very_good_core_template.dart
  test/helpers/test_multi_template_commands.dart
  test/src/commands/create/commands/flutter_app_test.dart
Labels: enhancement

#932 docs: include 'direct-overridden' in check licenses
  site/docs/commands/check_licenses.md
Labels: documentation

#933 chore: v0.19.1
  CHANGELOG.md
  lib/src/version.dart
  pubspec.yaml
Labels: chore
